### ISSUE TITLE
Error in computing cosine similarity with homomorphic encryption in aggregation phase when training TREC dataset using TextCNN

### ISSUE THREAD

**Issue by deepdarkfans** [InspiringGroup-Lab/martFL#1]
Hello, I am a PhD student who has just started studying homomorphic encryption. As the title shows, this error occurs at line 64 of `homo_encryption.py`, while everything is fine with training MNIST or using plaintext computation. I would like to ask if there are any settings I have not adjusted. Looking forward to your answer.

**Comment by deepdarkfans** [comment]
The error message is "RuntimeError: result ciphertext is transparent". I think this is an error that occurs when the plaintext or ciphertext parameters are all 0.

**Comment by liqi16** [comment]
Hi! Thanks for reporting this issue. It looks like you're hitting a transparent ciphertext exception because SEAL is compiled with `SEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=ON`. To fix this, rebuild SEAL with the flag set to `OFF`. You can try the command below:

```
cd SEAL-Python/SEAL

cmake -S . -B build -DSEAL_USE_MSGSL=OFF -DSEAL_USE_ZLIB=OFF -DSEAL_USE_ZSTD=OFF -DSEAL_THROW_ON_TRANSPARENT_CIPHERTEXT=OFF

cmake --build build 
```
This should stop the exception. Check the [SEAL Readme](https://github.com/microsoft/SEAL) for more on building SEAL.
